POC: wallet connect [WIP]
Psychedelic/plug-mobile pull request #225
Opened 2022-03-30 18:18 UTC by aleacevedo

# POC: wallet connect [WIP]

## Summarize

Proof of Concept of wallet connect implementation in mobile

2022-05-09 16:39 UTC, aleacevedo commented on src/helpers/navigation.js
> +  poppingCounter.isClosing = true;
But it is an object, you can modify an const object without problem

2022-05-09 16:39 UTC, aleacevedo commented on src/helpers/navigation.js
> +  poppingCounter.isClosing = false;
Same

2022-05-09 16:40 UTC, aleacevedo commented on src/helpers/navigation.js
> +export let TopLevelNavigationRef = createNavigationContainerRef();
I change the value at line 135

2022-05-09 19:40 UTC, aleacevedo commented on src/redux/store.js
> +};
I think so

2022-05-11 14:56 UTC, mattgle commented on src/constants/walletconnect.js
> +  icons: [],
Add comment to add plug's icon url

2022-05-11 14:56 UTC, mattgle commented on src/helpers/walletConnect.js
> +import { getAssets, sign } from '../redux/slices/user';
use alias

2022-05-11 14:57 UTC, mattgle commented on src/helpers/walletConnect.js
> +import { Buffer } from 'buffer';
Now we use utils insstead of helpers, move this to utils

2022-05-11 14:58 UTC, mattgle commented on src/helpers/walletConnect.js
> +};
Are those comments ok?

2022-05-11 15:16 UTC, mattgle requested changes
Great work!  A few comments!

2022-05-11 15:16 UTC, mattgle commented on src/navigation/index.js
> +    navigationRef?.navigate(Routes.LOGIN_SCREEN);
delete this

2022-05-11 15:16 UTC, mattgle commented on src/navigation/navigators/SwipeNavigator.js
> +import useDeepLink from '../../hooks/useDeepLink';
use alias

2022-05-11 15:16 UTC, mattgle commented on src/screens/WalletConnect/callRequest.js
> +import React, { useCallback, useState } from 'react';
Check other components or screens to see how we handle this

2022-05-11 15:16 UTC, mattgle commented on src/screens/WalletConnect/index.js
> +            <Text style={styles.title}>{`DAP NAME: ${dappName}`}</Text>
this can be improved

2022-05-11 15:16 UTC, mattgle commented on src/screens/WalletConnect/styles.js
> +import { Colors } from '../../constants/theme';
use aliases

2022-05-11 15:16 UTC, mattgle commented on src/screens/WalletConnect/styles.js
> +    resizeMode: 'contain',
check if this looks well on iphone SE and iphone X

2022-05-11 15:16 UTC, mattgle commented on src/utils/deepLink.js
> +} from '../redux/slices/walletconnect';
use aliases

2022-05-11 15:16 UTC, mattgle commented on src/utils/deepLink.js
> +  }
Can we do something here? Or maybe add a more detail comment

2022-05-11 15:16 UTC, mattgle commented on src/utils/deepLink.js
> +    }
is this ok????????

2022-05-12 18:06 UTC, merged